// src/components/ChangeMessage.vue
<template>
    <div>
        <p>Edit the home page message here:</p>
        <input :value="message" @input="setMessage" />
    </div>
</template>

<script>
import { mapState } from "vuex";

export default {
    name: "ChangeMessage",
    computed: {
        ...mapState(["message"]),
    },
    methods: {
        setMessage(e) {
            this.$store.commit("setMessage", e.target.value);
        },
    },
};
</script>

// src/components/ChangeMessage.jsx
import sharedState from "../services/sharedState";

export default {
    name: "ChangeMessage",
    setup() {
        const setMessage = (e) => {
            sharedState.message = e.target.value;
        };
        return () => (
            <div>
                <p>Edit the home page message here:</p>
                <input value={sharedState.message} onInput={setMessage} />
            </div>
        );
    },
};
