// client/src/components/Home.vue
<script>
import ChangeMessage from "./ChangeMessage.vue";
import MessageDisplay from "./MessageDisplay.vue";

export default {
  name: "Home",
  components: { ChangeMessage, MessageDisplay },
};
</script>

<template>
  <div>
    <img class="inline" alt="Vue logo" src="../assets/images/logo.png" />
    <MessageDisplay />
    <ChangeMessage />
  </div>
</template>

// src/components/Home.jsx
import ChangeMessage from "./ChangeMessage";
import logo from "../assets/images/logo.png";
import MessageDisplay from "./MessageDisplay";

const name = "Home";

const setup = () => () => (
    <div>
        <img alt="Vue logo" src={logo} />
        <MessageDisplay />
        <ChangeMessage />
    </div>
);

export default { name, setup };
