// src/components/Home.jsx
import MessageDisplay from "./MessageDisplay";
import ChangeMessage from "./ChangeMessage";

const name = "Home";

const setup = () => () => (
    <div>
        <img alt="Vue logo" src="/images/logo.png" />
        <MessageDisplay />
        <ChangeMessage />
    </div>
);

export default { name, setup };

// client/vue/Home.vue
<script>
import ChangeMessage from "./ChangeMessage.vue";
import MessageDisplay from "./MessageDisplay.vue";

export default {
  name: "Home",
  components: { ChangeMessage, MessageDisplay },
};
</script>

<template>
  <div>
    <img class="inline" alt="Vue logo" src="../images/logo.png" />
    <MessageDisplay />
    <ChangeMessage />
  </div>
</template>
